### ISSUE TITLE
[Feature Request] Option for moving Quoteblock above new message

### ISSUE THREAD

**Issue by vvesperr** [nirewen/Citador#10]
Would it be possible to style the output so that the Quoteblock is placed _above_ our new message instead of below it? It's way more intuitive to follow a conversation sequenced this way.

**Comment by nirewen** [comment]
Not possible cause I'm using Discord Embeds. Maybe in the future they'll add quotes to Discord and they will be above your message.

**Comment by vvesperr** [comment]
Ah, understood. Thanks for looking into it.
