### ISSUE TITLE
Include link to the quoted message

### ISSUE THREAD

**Issue by mio9** [nirewen/Citador#106]
![image](https://user-images.githubusercontent.com/11581624/54883165-3c9d7300-4ea6-11e9-9dbe-a9e340abbe86.png)
DIscord recently included this one, we could obtain a link to the quoted message by putting this link together with the message.
But it could be included into this plugin such that we don't have to copy and paste the llink everytime we want to quote

**Comment by nirewen** [comment]
With Citador you can jump to the quoted message by clicking in the author's name. I'll see if having this message link in the embed works too. If so, I'll change the code to this instead, and everyone will be able to jump to it using Citador or not.

**Comment by nirewen** [comment]
Eh, it doesn't work in the embed's author... It opens a new tab in my browser instead. When you post it in the chat, though, it works, even switched channels and servers.

You may use the current URL in the embed's author for now, if you want to jump to the message. Unfortunately, people not using Citador will be redirected to the plugin's page when trying to jump to the message by clicking the author.
