### ISSUE TITLE
No longer working with the new discord canary textbox thingy

### ISSUE THREAD

**Issue by P4risAndStuff** [nirewen/Citador#11]
So discord canary released this update to make the message-typing textarea look different and they changed the icons as well. Now Citador doesn't work and the message you're trying to quote doesn't appear above the textarea, and when you send the message there's no embed in your message that quotes the message you originally wanted to quote. This needs to be fixed, otherwise Citador will become useless forever.

**Comment by P4risAndStuff** [comment]
Well scratch that, betterdiscord is completely broken in the newest version of canary. RIP BD.

**Comment by nirewen** [comment]
I am developing a new pre-release for PTB and Canary right now! I'll be rolling it up in a few minutes. :D

**Comment by P4risAndStuff** [comment]
Everything's good now!
