### ISSUE TITLE
The plugin no longer works on 0.0.305 latest update

### ISSUE THREAD

**Issue by tryoutuser** [nirewen/Citador#110]
Due to recently new updates to discord stable, i can't no longer send quoted messages.

1. In chat list, button to quote is visible and functional. When i click over a message, quoted message appears normally above input column.

2. Trying to send, quoted messages from before did not attached to chat i sent.

3. Right click from guild/server icon to enable/disable embed quote has been not accesible since discord stable 0.0.304.

**Comment by TheTeusma** [comment]
Same bug here. Thanks for open ticket, @tryoutuser . Let's wait.

**Comment by 4r1sh** [comment]
Same issue for me.

**Comment by BreadIsPan** [comment]
its already fixed

**Comment by tryoutuser** [comment]
> its already fixed

Uh nope, still does not work on me.

**Comment by BreadIsPan** [comment]
use my https://github.com/BreadIsPan/citador-fix
