### ISSUE TITLE
Quoting from another server.

### ISSUE THREAD

**Issue by BrettplayMC** [nirewen/Citador#12]
When I try to quote from server #1, and then go to server #2, the quote disappears from both servers and then bugs out and I can't quote any more.

**Comment by davipatury** [comment]
[See this](https://github.com/nirewen/Citador/blob/pt/Citador.plugin.js#L537)

**Comment by vvesperr** [comment]
It's totally broken for me after the latest Discord update. Clicking the button does nothing. Must be the new message box facelift Discord implemented.

**Comment by maximmax42** [comment]
It doesn't work not only between servers, but between different channels on one server.

**Comment by BrettplayMC** [comment]
What do you mean davipatury?

**Comment by nirewen** [comment]
Fixed in [v1.5.7](https://github.com/nirewen/Citador/releases/tag/1.5.7)
