### ISSUE TITLE
Citador can't work anymore

### ISSUE THREAD

**Issue by Paulbouchara** [nirewen/Citador#120]
![image](https://user-images.githubusercontent.com/23699781/62416526-b3a8fc00-b63c-11e9-824a-6b9b40eb24c5.png)
This following error is cause by a missing library fetched from the web, which... doesn't exist anymore (or at least return 404) 
This is the link causing the issue
https://rauenzi.github.io/BetterDiscordAddons/Plugins/PluginLibrary.js

Cheers !

**Comment by ronelm2000** [comment]
Seems like that PluginLibrary has been moved to: https://raw.githubusercontent.com/rauenzi/BDPluginLibrary/master/release/0PluginLibrary.plugin.js
