### ISSUE TITLE
Request - Support for Quote Blocks

### ISSUE THREAD

**Issue by ronelm2000** [nirewen/Citador#121]
The idea is, instead of codeblocks, Citador instead would use the new `>>>` command from the [New Markdown Rules](https://support.discordapp.com/hc/en-us/articles/210298617-Markdown-Text-101-Chat-Formatting-Bold-Italic-Underline-)

**Comment by Soitora** [comment]
This, would look much better than using Code Blocks, and more of its intended use.

**Comment by shinji257** [comment]
I was taking a look at the support for message quotes in Discord and looks like they are handled like a normal message except for embedding images directly (when you paste directly into discord).  So the URL is still needed like it is done currently however if you put URLs in the links are automatically shown following the message.  Adding < before and > after the URL still prevents that like it would for normal messages.
