### ISSUE TITLE
[Bug] Quoting in PM doesn't send

### ISSUE THREAD

**Issue by DrowningElysium** [nirewen/Citador#122]
When I quote an older message of someone and send a message. The Quote stays in the bar and it doesn't get attached to the send message.

**Comment by GooodGamee** [comment]
[Citador.plugin.zip](https://github.com/nirewen/Citador/files/3517159/Citador.plugin.zip)
temporary fix

**Comment by DrowningElysium** [comment]
Thanks @GooodGamee, could you send a PR to the repo?

**Comment by GooodGamee** [comment]
done

**Comment by 7twin** [comment]
@GooodGamee I don't think the PR went through at least I can't find it?
