### ISSUE TITLE
"undefined" When hovering

### ISSUE THREAD

**Issue by mew351** [nirewen/Citador#16]
I don't know what causes this? I dont' think any of my other plugins conflict with this one
![image](https://user-images.githubusercontent.com/12377381/29008690-0d3604e8-7ad0-11e7-9b40-ddfc556bde88.png)

**Comment by mew351** [comment]
Makes it impossible to click on the quote button :/

**Comment by nirewen** [comment]
I think this was something about the locale thing. May have been fixed now. Ping me if this continues to happen.
