### ISSUE TITLE
Fazer a mensagem aparecer depois da citação

### ISSUE THREAD

**Issue by TrademarkTM** [nirewen/Citador#2]
~Eu ia escrever em inglês, mas lembrei que você fala português~
Então, apesar de não ser algo muito importante, seria legal que a mensagem aparecesse depois da citação, igual no Skype. Fica muito mais harmonioso e faz bem mais sentido.

Outras ideias ainda menos importantes:
- **citação dentro de outra citação:** provavelmente não dá pra fazer, então é só simplesmente transformar uma mensagem em 'code'.
- **selecionar diretamente a mensagem**: provavelmente não dá pra fazer², mas selecionar diretamente a mensagem que você quer citar (quando um usuário manda milhões de mensagens seguidas), pouparia muito trabalho.

Obrigado, e saiba que está fazendo um ótimo trabalho.
![qualidade](https://cloud.githubusercontent.com/assets/20507094/23002493/32cc797e-f3d2-11e6-80ed-dd3073d3ea10.png)

**Comment by nirewen** [comment]
Eu estou trabalhando nesse de selecionar a mensagem.
Eu fiz ele anteriormente, mas nunca ficava do jeito que eu queria, vou tentar de novo mais tarde.

E sobre a citação dentro de citação, é possível sim (mas não ficaria muito bonito).
Pra coisa de mensagem depois da citação, eu precisaria de 2 POSTs no canal (não sei se você entende)
Eu basicamente precisaria mandar 2 mensagens seguidas, o que poderia confundir todo o chat (eu já fiz isso antes) Ficava algo mais ou menos assim:
```
Nirewen - Hoje às 00:00
| quote blabla

Usuário 1 - Hoje às 00:00
alguma mensagem

Nirewen - Hoje às 00:00
mensagem que eu queria que saísse logo depois da citação
```
Ou seja, ela atrasava, confundindo todo o chat
Fora que depois o Discord poderia te dar um ratelimit, o que eu to tentando evitar por enquanto.
