### ISSUE TITLE
Request - Auto update

### ISSUE THREAD

**Issue by OrangutanGaming** [nirewen/Citador#25]

**Comment by nirewen** [comment]
I made a semi-auto-updater which is already done and set. 

'll be working on an auto-updater which will actually save the new file in your computer (hope that's not violating people's privacy tho)

Thanks for the suggestion :D

**Comment by brodycas3** [comment]
Just as a side comment, BetterRoleColors already does that. 
![image](https://user-images.githubusercontent.com/19770864/31945530-73d485b6-b89d-11e7-80be-af3245c80812.png)
