### ISSUE TITLE
Errors in console.

### ISSUE THREAD

**Issue by T1MOXA** [nirewen/Citador#26]
```Access to Font at 'https://crossorigin.me/https://nirewen.s-ul.eu/WJJ3bKJl.ttf' from origin 'https://discordapp.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://discordapp.com' is therefore not allowed access. The response had HTTP status code 503.```

**Comment by nirewen** [comment]
🤔 
That shouldn't be an issue...
I'll take a look at this once I get my hands back into the project.
Are you seeing the font anyway? I only use another font in the quote button, which is the icon thing.

**Comment by T1MOXA** [comment]
Yes, i see the icon

**Comment by nirewen** [comment]
Then this is just like a warning. Nothing to worry about...
