### ISSUE TITLE
Icon taller than chat line with decreased font scaling

### ISSUE THREAD

**Issue by Lavaflow** [nirewen/Citador#29]
I have discord on 90% chat font scaling, and with Citador installed the lines shift around when I move my mouse up and down the chat. I'm almost certain this is because the icon is larger than the line of text, so when the icon to quote shows up it shoves things (i don't know whether up or down) so that it fits on only one line. It's not a large issue, but it's one of those things that don't stop bothering you once you notice it. 
I don't know how easy/simple it would be, but the obvious (to me) solution would be to scale the icon with the chat font scaling.

**Comment by nirewen** [comment]
I've set my font scaling to 90% and this doesn't happen to me. Can you record a GIF or something? If it's just a CSS problem you won't have to download the plugin again, just wait for the style to update itself :D

**Comment by Lavaflow** [comment]
Huh. I just re-enabled the plugin to make a gif of it and it wasn't happening for me either, which seems a little bizarre to me. I'll leave it enabled and I'll record it and put here if it spontaneously starts happening again.
Also a couple things that in retrospect I should have mentioned in my first post: I also have the zoom level at 75, and I only have one other plugin, which is "Better Role Colors"

**Comment by Lavaflow** [comment]
So the next day after a system restart, it's come back:
https://imgur.com/SvHjuoQ

I also notice that the icon is different- a curved arrow instead of whatever it was yesterday (quotation marks? I don't truly recall)
