### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by HYPExMon5ter** [nirewen/Citador#32]
For the first request, I don't know if you've ever used [Quoter](https://github.com/samogot/betterdiscord-plugins/blob/master/v1/quoter.plugin.js), but in Quoter you can click the name of the person who said the quote inside the embed and it'll scroll to where that person said what you quoted.

Also, another request would to add a setting where you can disable using embeds for certain servers, but instead use plain text and code blocks (like Quoter does), because some servers don't allow embeds.

**Comment by nirewen** [comment]
Implemented in 1.7
Thanks for the suggestion! :D
