### ISSUE TITLE
It's (kinda) possible to mention while quoting

### ISSUE THREAD

**Issue by theanidox** [nirewen/Citador#4]
Just turn on Developer Mode (`Settings > Appearance`) then copy the users ID.
![Right click on the person, copy ID](https://cloud.githubusercontent.com/assets/24899167/24718294/66b99e7a-1a2d-11e7-9be9-23c66741f436.png)

Then press `Quote`, and instead of @'ing them normally, type this:
`<@TheirID>`
![Example 1](https://cloud.githubusercontent.com/assets/24899167/24718546/48335f9e-1a2e-11e7-9e48-1be683e6926c.png)

![Example 2](https://cloud.githubusercontent.com/assets/24899167/24718574/6a9ca1c6-1a2e-11e7-8fe9-59cd7502a417.png)

Could there be a way you could, when sending the message, change regular mentions to `<@MentionedUsersID>` ?

**Comment by nirewen** [comment]
I know you can use this, but not everyone want to copy people's id just to be able to quote someone.
I would try to replace every mention with the user id, if BD helped me ~~damn BD why did you remove the  function~~
