### ISSUE TITLE
Suggestion: Better Quote button

### ISSUE THREAD

**Issue by SimonMattila** [nirewen/Citador#45]
I love the preview function with your quote program but going from using [https://github.com/samogot/betterdiscord-plugins/tree/master/v2/Quoter](this), I certainly miss having a button that looks official and fits in better.

Like this at the right side of the message
![image](https://user-images.githubusercontent.com/10836780/33243762-7bde5fc0-d2ec-11e7-8856-57fa809f3432.png)

**Comment by rauenzi** [comment]
You can just use a theme/some CSS to change the icon to whatever you want.

**Comment by OrangutanGaming** [comment]
I mean there could be a toggle for having it on the side of message like that, but the image itself depends.

**Comment by rauenzi** [comment]
Having it on the side would change the functionality of Citador. Currently all messages from that group are loaded into the preview and you use the little trash icon to remove individual ones. If it is on the side of every message it wouldnt make sense to have it preview all messages of the group so youd only be able to do a single message. And without the multi-quoting removes functionality from Citador

**Comment by SimonMattila** [comment]
What that other alllows you to do is normal click for the entire group of messages and alt/ctrl click for a single message, so functionality could be kept
