### ISSUE TITLE
Citador 1.7.2 [Solved]

### ISSUE THREAD

**Issue by iYatsumi** [nirewen/Citador#50]
i can't quote from server to server nor over channels anymore while i could in the previous version.

**Comment by nirewen** [comment]
Are you using @rauenzi's BD fork?

Em 20 de jan de 2018 20:21, "Anh" <notifications@github.com> escreveu:

**Comment by iYatsumi** [comment]
im not sure what that is but i just updated betterdiscord and citador with it and i got those issues

**Comment by nirewen** [comment]
I recommend you to use [@rauenzi's fork](https://github.com/rauenzi/BetterDiscordApp/releases/tag/0.2.82). It fixes many errors

**Comment by iYatsumi** [comment]
Thank you it fixed the issues !
