### ISSUE TITLE
Request: Typed Text Below Quote

### ISSUE THREAD

**Issue by AceFool** [nirewen/Citador#53]
I would prefer that the text that I type be below the quote. If this could be added as an option at least, it would be greatly appreciate.

**Comment by intrnl** [comment]
With the way embeds work in Discord, this isn't really possible to do unless you send the quote first and then the reply which basically means two separate messages.

**Comment by AceFool** [comment]
It works with the Quoter plugin, but unfortunately, Quoter is inferior in that it does not show a quote preview, quotes are less customizable (can't remove lines between others), and it has an additional plugin dependency. Also Quoter just randomly stops working for me.

**Comment by rauenzi** [comment]
The reason it looks that way with quoter is because it sends the quote as a message first, then sends your typed message afterwards, exactly as @intrnl mentioned

**Comment by nirewen** [comment]
I'm not doing that. Probably in the future, when Discord oficially add quotes to the core, they make it show above the message.
