### ISSUE TITLE
quote different channel

### ISSUE THREAD

**Issue by krazyito65** [nirewen/Citador#55]
I use to be able to quote from one channel, and submit it in another, but this doesn't seem to happen any more, is there a reason?

**Comment by nirewen** [comment]
Better Discord by Jiiks is broken. Use [rauenzi's fork](http://github.com/rauenzi/BetterDiscordApp/releases) instead. It's hightly recommended. Fixes a lot of broken stuff Jiiks' too busy to fix (because he's working on BDv2 :wink:)

**Comment by krazyito65** [comment]
Thanks!
