### ISSUE TITLE
Broken?

### ISSUE THREAD

**Issue by HYPExMon5ter** [nirewen/Citador#56]
The latest update seems to have broken this, there is no quote button anymore.

**Comment by LasseNiermann** [comment]
Did you activate it in the plugin settings? Join the support server and we can help you!
https://discord.gg/rBRCyp

**Comment by HYPExMon5ter** [comment]
Of course, I’ve been using it for months, but after the last discord update, the quote button isn’t showing up

**Comment by HYPExMon5ter** [comment]
Still an issue, button doesn't show up when loading better discord, a fix is to disable then re-enable the plugin.

**Comment by rauenzi** [comment]
Cannot reproduce, using it on all 3 versions of discord without issue. It seems it's just you

**Comment by HYPExMon5ter** [comment]
It's fixed now, I switched to BD instead of using your fork and everything loads fine now.
