### ISSUE TITLE
Error on disabling the plugin

### ISSUE THREAD

**Issue by HYPExMon5ter** [nirewen/Citador#57]
![image](https://user-images.githubusercontent.com/12315186/36571069-00696b94-1803-11e8-89b6-c9585e207beb.png)

**Comment by rauenzi** [comment]
this only happens if you had a startup issue

**Comment by HYPExMon5ter** [comment]
It's fixed now, I was running your fork because BD was broken, and I never switched back to BD, I just did and it loads just fine.
