### ISSUE TITLE
Colon character : occasionally stops quote from being sent

### ISSUE THREAD

**Issue by kaloncpu57** [nirewen/Citador#6]
If you try to quote a message and your own message contains a colon with a space in front of it, your message will send without the quote.
![discord-quote-plugin](https://cloud.githubusercontent.com/assets/10432938/25521666/c475dfaa-2bbd-11e7-9d88-e13e1a8cf5f6.gif)

(However, if you have a second colon after the first, this doesn't happen at all.)

**Comment by theanidox** [comment]
Maybe delete the message and try again if it fails to send the embed or send the message first then the embed (if that's not what already happens).

**Comment by kaloncpu57** [comment]
Deleting the message and trying again does not work, but yes you can send the embed by itself afterward.
I mostly wanted to make sure this wasn't a bug that might want to be fixed.

**Comment by nirewen** [comment]
I really don't know why this happens. If your text cursor (the | thing) is next to an emoji (a thing that would be an emoji but you disabled it in settings), the message will send without triggering my plugin.
For now, don't put your text cursor next to an emoji and you'll be fine.

![??](http://nirewen.s-ul.eu/B4cYACx1.gif)
