### ISSUE TITLE
Ability to "collapse" a quoted message

### ISSUE THREAD

**Issue by mtaki14** [nirewen/Citador#69]
Would it be possible to add a way to collapse or cut off part of the quoted message? It would be useful for quoting walls of text. 

My use-case though has to do with creating a table of contents of sorts for an announcements/news channel to consolidate everything into topics when a lot of "news" are posted at once.

**Comment by rauenzi** [comment]
That's a limitation of Discord. Their embeds do not support that feature and we can't make their embed support that feature. Best that is possible would be having the feature only show for you while everyone else still has a wall of text so not worthwhile to implement.

**Comment by mtaki14** [comment]
I see. Yeah, makes sense it being a limitation on discord's API. Otherwise it would had been available by now I guess.
