### ISSUE TITLE
Is citador using discord API?

### ISSUE THREAD

**Issue by nblockbuster2500** [nirewen/Citador#76]

**Comment by intrnl** [comment]
It uses Discord client's internals function to send quotes.

**Comment by KaKi87** [comment]
Does it means it's not a self-bot ?

**Comment by nirewen** [comment]
@KaKi87 it can look like you're using a self-bot, as normal people can't embed other than using internal functions or direct API calls.

**Comment by KaKi87** [comment]
How can I prove it to them ?
