### ISSUE TITLE
Can't use citador after update

### ISSUE THREAD

**Issue by anhxtaiii** [nirewen/Citador#78]
There was an update last night on discord, upon relaunch citador also had an update. This morning when i went on discord again the option to quote with citador wasn't there anymore for some reason so i tried using the bandage and update again just to be sure but nothing changed. 

Using version v1.7.8

**Comment by SilverDash** [comment]
Yep. I'm not sure what you did when you updated the plugin. On the surface it looked like you did nothing at all. 

Hopefully there is an easy fix.

**Comment by nirewen** [comment]
I fixed this but didn't change the version. I guess you guys already had the 1.7.8 when I pushed this fix. I'll try to force an update so everyone who got the plugin with this bug will update to the correct file.

**Comment by anhxtaiii** [comment]
I downgraded back to v1.7.2 but I guess that didn't really help.

**Comment by anhxtaiii** [comment]
Gonna wait for the new update i guess
