### ISSUE TITLE
Citador won't show messages being trashed

### ISSUE THREAD

**Issue by Aida-Enna** [nirewen/Citador#80]
Sorry for the crappy title name, I don't know what else to call it. When I quote someone who did multiple messages, I used to be able to click on the trash can and only quote the message I want. After the latest update, the trash can is still there (and the functionality works), but the message doesn't remove from the preview. Here's a gif of what I mean:

https://gfycat.com/NeatFakeFlyinglemur

**Comment by nirewen** [comment]
Ah, I get it.
