### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by rampureadi** [nirewen/Citador#83]
Quoted message is not properly shown but normal text
![screenshot_644](https://user-images.githubusercontent.com/42176494/43776176-a76403be-9a6c-11e8-924a-944f9531b6c6.jpg)

**Comment by nirewen** [comment]
Make sure you select one of these in the plugin's settings. It's `Always` by default.
![image](https://user-images.githubusercontent.com/8761479/43931373-75b6ac1e-9c14-11e8-96ec-7110e98b4731.png)
