### ISSUE TITLE
Quoting not showing up correctly

### ISSUE THREAD

**Issue by MrStealYourCat** [nirewen/Citador#87]
![aa](https://user-images.githubusercontent.com/43421978/45777708-96d22880-bc24-11e8-8951-7937e35632dd.png)
![a](https://user-images.githubusercontent.com/43421978/45777709-96d22880-bc24-11e8-8250-f42927b47b78.gif)

I've tried fiddling around, but I can't make the quote look like it does in the preview. Am I missing something?

**Comment by nirewen** [comment]
Go to the plugin's settings and enable embeds. It's in codeblock form by default.
User Settings > BetterDiscord > Plugins > Citador > Settings

**Comment by MrStealYourCat** [comment]
Thank you!
