### ISSUE TITLE
Plugin resets Discord's zoom level on startup

### ISSUE THREAD

**Issue by gamingfail123** [nirewen/Citador#9]
Everything's said in the title.
Despite that this is just an awesome plugin. :D

**Comment by nirewen** [comment]
Are you sure that my plugin is resetting the zoom level?
I didn't make anything to reset it and don't even know what can be doing that.
Can you try desabling all plugins but mine, or disabling all plugins?
Cause I set my zoom level to greater than 100%, restarted Discord and/or my plugin, didn't reset the zoom level tough.
