### ISSUE TITLE
Graphical Bug With Quoting

### ISSUE THREAD

**Issue by Delphince** [nirewen/Citador#94]
With the 1.7.15 update, the quote icon no longer disappears after mouseover in the Discord message display, as long as there is more than one consecutive message from the same user. If there is only a single message before a different user comments, the icon still disappears correctly.

**Comment by dimon222** [comment]
Same problem, any clue ?

**Comment by willjkeller** [comment]
After some investigation, you can fix this by disabling "Normalize Classes" in BetterDiscord's Bandages section.

**Comment by WayoshiM** [comment]
On line 192 of version 1.7.18, if you change the condition from equaling 1 to at least 1, I got this issue to fix.

**Comment by budak7273** [comment]
What @WayoshiM said works, except it's on line 195 of the version in place as of this comment.
