### ISSUE TITLE
Discord update broke the plugin

### ISSUE THREAD

**Issue by williamjcm** [nirewen/Citador#95]
As of yesterday (11 Jan 2019), Citador stopped working.

I can still access the settings, but hovering over a message group doesn't display the quote button anymore.

I don't remember if there was a context menu entry, but if there was one, it's not there anymore either.

There are no errors in the console.

If you need more information, don't hesitate to ask.

**Comment by MoofMonkey** [comment]
Can confirm this, PTR broke like several days ago.

**Comment by MoofMonkey** [comment]
`$(`${DiscordSelectors.Messages.messages} ${DiscordSelectors.Messages.container}`).on('mouseover', function() {`
That's not working
![image](https://user-images.githubusercontent.com/11695747/51071373-fa171900-1660-11e9-8b68-03aa3ae1f018.png)

**Comment by MoofMonkey** [comment]
Looks like DiscordSelectors broke, not Citador. Will try to fix asap, and open PR.

**Comment by SHADOWDANCH** [comment]
If remove `${DiscordSelectors.Messages.messages} ` on line 100 it start working.

**Comment by MoofMonkey** [comment]
Made PR, ty @SHADOWDANCH

**Comment by SHADOWDANCH** [comment]
@MoofMonkey i think it's not true fix

**Comment by lzrdblzzrd** [comment]
but it works :^)

**Comment by SHADOWDANCH** [comment]
Or in lines 68-70 change `messages` to `messages-3amgkR` i think it better solution

**Comment by lzrdblzzrd** [comment]
@SHADOWDANCH what is `3amgkR`?

**Comment by SHADOWDANCH** [comment]
> @SHADOWDANCH what is `3amgkR`?

`messages-3amgkR` element name or something.

**Comment by rauenzi** [comment]
A better fix would be to change line 100 from
```js
$(`${DiscordSelectors.Messages.messages} ${DiscordSelectors.Messages.container}`)
```
to
```js
$(`.${DiscordSelectors.Messages.messages.toString().split(".")[1]} ${DiscordSelectors.Messages.container}`)
```

**Comment by williamjcm** [comment]
This fix works on my end.

Leaving this issue open until the plugin is officially fixed by nirewen.

**Comment by WhiskeredMaster** [comment]
Can confirm that too.

**Comment by williamjcm** [comment]
So, apparently, there was a Discord update that broke many plugins, and Citador is once again one of those.

**Comment by tryoutuser** [comment]
I've got the same problem like williamjcm's case. Cannot start and stop citador plugin.

**Comment by SHADOWDANCH** [comment]
TempFix: remove line 56

**Comment by nirewen** [comment]
This should've been fixed by now.
